[project]
name = "tanvivarangal"
version = "1.0.0"
description = ""
authors = [
    { name = "Julien Malard-Adam", email = "julien.malard@mail.mcgill.ca" },
]
dependencies = [
    "bibtexparser<2.0.0,>=1.4.0",
    "ennikkai<2.0.0,>=1.2.6",
    "pyfranc<1.0.0,>=0.1.1",
    "deepmerge<2.1.0,>=2.0",
    "odfdo>=3.9.1",
    "nuchabal>=0.1.7",
    "python-iso639>=2026.4.20",
    "babel>=2.18.0",
]
requires-python = ">=3.12,<4.0"
readme = "README.md"
license = { text = "AGPL-3.0" }

[tool.pdm.build]
includes = ["src/தன்விவரங்கள்"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "pytest<9.0.4,>=9.0.3",
    "coverage>=7.8.0",
    "twine>=6.2.0",
]
